[package]
name = "wasm-junction-example-reload"
description = "Self-contained hot-reload example"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish = false
build = "build.rs"

[[bin]]
name = "wasm-junction-example-reload"
path = "src/main.rs"
test = false

[lints]
workspace = true

[dependencies]
wasm-junction = { path = "../../crates/wasm-junction", version = "=0.0.0" }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { version = "1", features = ["macros", "rt"] }

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = "=0.3.77"
