[package]
name = "wasm-junction"
description = "Engine-neutral APIs for composing WebAssembly components"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
wasmparser = { version = "=0.259.0", default-features = false, features = ["component-model", "std"] }

[dev-dependencies]
wit-component = { version = "=0.259.0", default-features = false, features = ["dummy-module"] }
wit-parser = { version = "=0.259.0", default-features = false, features = ["std"] }
