[package]
name = "wasm-junction"
description = "Engine-neutral APIs for composing WebAssembly components"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish.workspace = true

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]

[lints]
workspace = true

[features]
default = ["wasmtime"]
wasmtime = ["dep:wasm-junction-wasmtime"]

[dependencies]
wasm-junction-core = { path = "../wasm-junction-core", version = "=0.0.0" }
wasm-junction-macros = { path = "../wasm-junction-macros", version = "=0.0.0" }
wasmparser = { version = "=0.259.0", default-features = false, features = ["component-model", "std", "validate"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
wasm-junction-wasmtime = { path = "../wasm-junction-wasmtime", version = "=0.0.0", optional = true }

# A future `jco` feature will add the browser engine here.
[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]

[dev-dependencies]
wit-component = { version = "=0.259.0", default-features = false, features = ["dummy-module"] }
wit-parser = { version = "=0.259.0", default-features = false, features = ["std"] }
