[workspace]
resolver = "3"
members = ["cycle-a", "cycle-b", "notes-summary", "resource-client", "translator", "writer"]

[workspace.package]
edition = "2024"
version = "0.0.0"
publish = false

[workspace.dependencies]
wit-bindgen = { version = "=0.62.0", features = ["async"] }

[profile.release]
panic = "abort"
