//! Generated byte-stream binding surfaces.

#![forbid(unsafe_code)]

mod support;

use wasm_junction::{
    App, CallContext, Component, InputStream, OutputStream, StreamHandle, TypedCall,
};

wasm_junction::bindgen!({ path: "tests/fixtures/streams/wit" });

struct Echo;

impl host::Host for Echo {
    async fn top(&self, _cx: &CallContext, value: InputStream) -> OutputStream {
        OutputStream::from_bytes(value.read_all().await.unwrap())
    }

    async fn optional(
        &self,
        _cx: &CallContext,
        value: Option<InputStream>,
    ) -> Option<OutputStream> {
        match value {
            Some(value) => Some(OutputStream::from_bytes(value.read_all().await.unwrap())),
            None => None,
        }
    }

    async fn choose(
        &self,
        _cx: &CallContext,
        value: Result<InputStream, InputStream>,
    ) -> Result<OutputStream, OutputStream> {
        match value {
            Ok(value) => Ok(OutputStream::from_bytes(value.read_all().await.unwrap())),
            Err(value) => Err(OutputStream::from_bytes(value.read_all().await.unwrap())),
        }
    }
}

fn app() -> (App, guest::Guest) {
    let app = App::builder()
        .engine(support::FakeEngine)
        .provide(host::provider(Echo))
        .build()
        .unwrap();
    let component = Component::from_bytes(support::component_bytes(
        include_str!("fixtures/streams/wit/package.wit"),
        "plugin",
    ))
    .unwrap()
    .named("echo");
    support::block_on(app.load(component)).unwrap();
    let handle = app.get::<guest::Guest>("echo").unwrap();
    (app, handle)
}

fn bytes(stream: InputStream) -> Vec<u8> {
    support::block_on(stream.read_all()).unwrap()
}

#[test]
fn app_maps_streams_at_top_level_and_inside_option_and_result() {
    let (_app, handle) = app();
    assert_eq!(
        bytes(support::block_on(handle.top(OutputStream::from_bytes(b"top"))).unwrap()),
        b"top"
    );
    assert_eq!(
        support::block_on(handle.optional(None)).unwrap().map(bytes),
        None
    );
    assert_eq!(
        support::block_on(handle.optional(Some(OutputStream::from_bytes(b"some"))))
            .unwrap()
            .map(bytes),
        Some(b"some".to_vec())
    );
    for value in [Ok(b"ok".as_slice()), Err(b"err".as_slice())] {
        let expected = value.map(<[u8]>::to_vec).map_err(<[u8]>::to_vec);
        let value = value
            .map(OutputStream::from_bytes)
            .map_err(OutputStream::from_bytes);
        let actual = support::block_on(handle.choose(value))
            .unwrap()
            .map(bytes)
            .map_err(bytes);
        assert_eq!(actual, expected);
    }
}

#[test]
fn typed_call_views_keep_opaque_stream_handles() {
    let stream = StreamHandle::from(OutputStream::from_bytes(b"opaque"));
    let id = stream.id();
    let values = guest::Top { value: stream }.into_vals();
    let decoded = guest::Top::from_vals(&values).unwrap();
    assert_eq!(decoded.value.id(), id);
}
