//! Tests for generated byte-list conversions.

#![forbid(unsafe_code)]

use wasm_junction::{Call, Caller, TypeError, TypedCall, Val};

wasm_junction::bindgen!({ path: "tests/fixtures/bytes/wit" });

#[test]
fn byte_lists_use_the_canonical_bytes_value() {
    let bytes = vec![0, 127, 255];
    let values = codec::Echo {
        value: bytes.clone(),
    }
    .into_vals();
    assert_eq!(values, [Val::Bytes(bytes.clone())]);
    assert_eq!(codec::Echo::from_vals(&values).unwrap().value, bytes);
    assert_eq!(
        codec::Echo::decode_output(&codec::Echo::output(vec![1, 2])).unwrap(),
        [1, 2]
    );
}

#[test]
fn byte_lists_reject_the_element_value_shape() {
    let call = Call::new(
        Caller::Host,
        "codec",
        codec::INTERFACE,
        "echo",
        vec![Val::List(vec![Val::U8(1)])],
    );
    let Err(error) = call.view::<codec::Echo>() else {
        panic!("element-shaped byte list was accepted")
    };
    assert_eq!(error, TypeError::new("expected echo list"));
}
