//! Generated byte-stream binding surfaces.

#![forbid(unsafe_code)]

mod support;

use wasm_junction::{
    App, Call, CallContext, CallError, Component, InputStream, Middleware, Next, OutputStream,
    StreamHandle, TypedCall, Val, Vals,
};

wasm_junction::bindgen!({ path: "tests/fixtures/streams/wit" });

struct Echo;

struct TransformStreams;

impl Middleware for TransformStreams {
    async fn call(&self, call: Call, next: Next) -> Result<Vals, CallError> {
        let function = call.function.clone();
        let mut values = next.run(call).await?;
        if let Some(Val::Stream(stream)) = values.first_mut() {
            *stream = match function.as_ref() {
                "top" => stream.take().map_chunks(|mut bytes| {
                    bytes.make_ascii_uppercase();
                    bytes
                }),
                "records" => stream.take().filter_items(|item| {
                    !matches!(item, Val::Record(fields) if matches!(
                        fields.first(), Some((_, Val::String(title))) if title == "second"
                    ))
                }),
                _ => return Ok(values),
            };
        }
        Ok(values)
    }
}

impl host::Host for Echo {
    async fn top(&self, _cx: &CallContext, value: InputStream) -> Result<OutputStream, CallError> {
        Ok(OutputStream::from_bytes(value.read_all().await?))
    }

    async fn records(
        &self,
        _cx: &CallContext,
        value: InputStream<host::Note>,
    ) -> Result<OutputStream<host::Note>, CallError> {
        Ok(OutputStream::from_items(value.read_all().await?))
    }

    async fn optional(
        &self,
        _cx: &CallContext,
        value: Option<InputStream>,
    ) -> Result<Option<OutputStream>, CallError> {
        Ok(match value {
            Some(value) => Some(OutputStream::from_bytes(value.read_all().await?)),
            None => None,
        })
    }

    async fn choose(
        &self,
        _cx: &CallContext,
        value: Result<InputStream, InputStream>,
    ) -> Result<Result<OutputStream, OutputStream>, CallError> {
        Ok(match value {
            Ok(value) => Ok(OutputStream::from_bytes(value.read_all().await?)),
            Err(value) => Err(OutputStream::from_bytes(value.read_all().await?)),
        })
    }
}

fn app() -> (App, guest::Guest) {
    let app = App::builder()
        .engine(support::FakeEngine)
        .middleware(TransformStreams)
        .provide(host::provider(Echo))
        .build()
        .unwrap();
    let component = Component::from_bytes(support::component_bytes(
        include_str!("fixtures/streams/wit/package.wit"),
        "plugin",
    ))
    .unwrap()
    .named("echo");
    support::block_on(app.load(component)).unwrap();
    let handle = app.get::<guest::Guest>("echo").unwrap();
    (app, handle)
}

fn bytes(stream: InputStream) -> Vec<u8> {
    support::block_on(stream.read_all()).unwrap()
}

#[test]
fn app_maps_streams_at_top_level_and_inside_option_and_result() {
    let (_app, handle) = app();
    assert_eq!(
        bytes(support::block_on(handle.top(OutputStream::from_bytes(b"top"))).unwrap()),
        b"TOP"
    );
    assert_eq!(
        support::block_on(handle.optional(None)).unwrap().map(bytes),
        None
    );
    assert_eq!(
        support::block_on(handle.optional(Some(OutputStream::from_bytes(b"some"))))
            .unwrap()
            .map(bytes),
        Some(b"some".to_vec())
    );
    for value in [Ok(b"ok".as_slice()), Err(b"err".as_slice())] {
        let expected = value.map(<[u8]>::to_vec).map_err(<[u8]>::to_vec);
        let value = value
            .map(OutputStream::from_bytes)
            .map_err(OutputStream::from_bytes);
        let actual = support::block_on(handle.choose(value))
            .unwrap()
            .map(bytes)
            .map_err(bytes);
        assert_eq!(actual, expected);
    }
}

#[test]
fn generated_handles_and_hosts_convert_record_streams() {
    let (_app, handle) = app();
    let output = OutputStream::from_items([
        guest::Note {
            title: "first".to_owned(),
        },
        guest::Note {
            title: "second".to_owned(),
        },
    ]);
    let input = support::block_on(handle.records(output)).unwrap();
    assert_eq!(
        support::block_on(input.read_all()).unwrap(),
        [guest::Note {
            title: "first".to_owned()
        }]
    );
}

#[test]
fn typed_call_views_keep_opaque_stream_handles() {
    let stream = StreamHandle::from(OutputStream::from_bytes(b"opaque"));
    let id = stream.id();
    let values = guest::Top { value: stream }.into_vals();
    let decoded = guest::Top::from_vals(&values).unwrap();
    assert_eq!(decoded.value.id(), id);
}
