package example:dispatch@0.1.0;

interface pinger {
  ping: func(value: u32) -> u32;
}

interface runner {
  echo-bytes: func(bytes: list<u8>) -> list<u8>;
  imports: func(iterations: u32) -> u32;
  noop: func() -> u32;
}

world dispatch {
  import pinger;
  export runner;
}
