[package]
name = "wasm-junction-jco"
description = "Browser component engine for wasm-junction"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
js-component-bindgen = "=2.13.0"
wasm-junction-core = { path = "../wasm-junction-core", version = "=0.0.0" }

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "=0.3.104"
wasm-bindgen = "=0.2.127"
wasm-bindgen-futures = "=0.4.77"

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = "=0.3.77"
wasm-encoder = "=0.259.0"

[dev-dependencies]
wasm-junction-conformance = { path = "../wasm-junction-conformance", version = "=0.0.0" }
