package example:resources@1.0.0;

interface host {
    resource file;

    open-file: func(name: string) -> file;

    resource session {
        constructor(user: string);
        profile: func() -> string;
    }
    sessions: func(users: list<string>) -> stream<session>;
    accept-sessions: async func(values: stream<session>) -> string;
}

interface client {
    use host.{session};

    run: func(trap: bool) -> string;
    use-host-sessions: async func() -> list<string>;
    use-sessions: async func(values: stream<session>) -> list<string>;
    send-invalid-sessions: async func() -> string;
}

world resource-stream {
    import host;
    export client;
}
